#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONDA_ENV="${CONDA_ENV:-lerobot51}"

if [[ -z "${CAPTURE_PYTHON_BIN:-}" ]]; then
  if ! command -v conda >/dev/null 2>&1; then
    echo "[capture-app] ERROR: conda is unavailable and CAPTURE_PYTHON_BIN is unset." >&2
    exit 2
  fi
  CONDA_ENV_PREFIX="$(
    conda env list | awk -v env_name="${CONDA_ENV}" '$1 == env_name {print $NF; exit}'
  )"
  if [[ -z "${CONDA_ENV_PREFIX}" ]]; then
    echo "[capture-app] ERROR: conda environment not found: ${CONDA_ENV}" >&2
    exit 2
  fi
  CAPTURE_PYTHON_BIN="${CONDA_ENV_PREFIX}/bin/python"
fi
if [[ ! -x "${CAPTURE_PYTHON_BIN}" ]]; then
  echo "[capture-app] ERROR: environment Python is not executable: ${CAPTURE_PYTHON_BIN}" >&2
  exit 2
fi
CAPTURE_ENV_PREFIX="$(cd "$(dirname "${CAPTURE_PYTHON_BIN}")/.." && pwd)"

if [[ -z "${LEROBOT_ROOT:-}" ]]; then
  echo "[capture-app] ERROR: LEROBOT_ROOT is required." >&2
  echo "[capture-app] Copy config/lab_5090.env.example to config/lab_5090.env and set the compatible LeRobot checkout path." >&2
  exit 2
fi
if [[ ! -d "${LEROBOT_ROOT}/src/lerobot" || ! -f "${LEROBOT_ROOT}/tools/bi_x5_capture_app.py" ]]; then
  echo "[capture-app] ERROR: invalid LEROBOT_ROOT=${LEROBOT_ROOT}" >&2
  echo "[capture-app] Expected src/lerobot/ and tools/bi_x5_capture_app.py." >&2
  exit 2
fi
LEROBOT_ROOT="$(cd "${LEROBOT_ROOT}" && pwd)"

cd "$PROJECT_ROOT"

TASK_INDEX="${TASK_INDEX:-both}"
FPS="${FPS:-50}"
NUM_EPISODES="${NUM_EPISODES:-300}"
EPISODE_TIME_S="${EPISODE_TIME_S:-60000}"
CAPTURE_UI_HOST="${CAPTURE_UI_HOST:-0.0.0.0}"
CAPTURE_UI_PORT="${CAPTURE_UI_PORT:-8766}"
CAPTURE_OPEN_BROWSER="${CAPTURE_OPEN_BROWSER:-true}"
VCODEC="${VCODEC:-auto}"
STREAMING_ENCODING="${STREAMING_ENCODING:-true}"
ENCODER_THREADS="${ENCODER_THREADS:-1}"
ENCODER_QUEUE_MAXSIZE="${ENCODER_QUEUE_MAXSIZE:-600}"
TACTILE_STREAMING_ENCODING="${TACTILE_STREAMING_ENCODING:-true}"
TACTILE_ENCODER_THREADS="${TACTILE_ENCODER_THREADS:-1}"
TACTILE_ENCODER_NICE="${TACTILE_ENCODER_NICE:-10}"
TACTILE_RAW_SPOOL_FINISH_TIMEOUT_S="${TACTILE_RAW_SPOOL_FINISH_TIMEOUT_S:-900}"
OPENCV_NUM_THREADS="${OPENCV_NUM_THREADS:-1}"
OPENCV_OPENCL="${OPENCV_OPENCL:-false}"

case "${TASK_INDEX,,}" in
  0|right|right_arm|r) TASK_SLUG="right" ;;
  1|left|left_arm|l) TASK_SLUG="left" ;;
  2|both|bimanual|bi) TASK_SLUG="both" ;;
  3|open_lid|cup_lid|lid) TASK_SLUG="open_lid" ;;
  *) TASK_SLUG="$(printf '%s' "$TASK_INDEX" | tr -cs '[:alnum:]_' '_' | sed 's/^_//;s/_$//')" ;;
esac
TASK_SLUG="${TASK_SLUG:-task}"
RUN_TIMESTAMP="${RUN_TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
RUN_NAME_PREFIX="${RUN_NAME_PREFIX:-${RUN_NAME:-kd_tacmae_force_${TASK_SLUG}}}"
if [[ "${RUN_NAME_EXACT:-false}" =~ ^(1|true|yes|on)$ ]]; then
  RUN_NAME="$RUN_NAME_PREFIX"
else
  RUN_NAME="${RUN_NAME_PREFIX}_${RUN_TIMESTAMP}"
fi
DATASET_BASE_DIR="${DATASET_BASE_DIR:-${PROJECT_ROOT}/dataset}"
DATASET_ROOT="${DATASET_ROOT:-${DATASET_BASE_DIR%/}/${RUN_NAME}}"
DATASET_REPO_ID="${DATASET_REPO_ID:-local/${RUN_NAME}}"

CONNECT_WRIST_CAMERA="${CONNECT_WRIST_CAMERA:-true}"
CONNECT_LOCAL_CAMERAS="${CONNECT_LOCAL_CAMERAS:-false}"
CONNECT_SHARED_CAMERAS="${CONNECT_SHARED_CAMERAS:-false}"
CONNECT_GRIPPER="${CONNECT_GRIPPER:-true}"
CONNECT_D405_CAMERA="${CONNECT_D405_CAMERA:-false}"
D405_CAMERA_NAME="${D405_CAMERA_NAME:-cam_d405_color}"
D405_CAMERA_DEVICE="${D405_CAMERA_DEVICE:-/dev/video4}"
D405_CAMERA_WIDTH="${D405_CAMERA_WIDTH:-640}"
D405_CAMERA_HEIGHT="${D405_CAMERA_HEIGHT:-480}"
D405_CAMERA_FPS="${D405_CAMERA_FPS:-30}"
D405_CAMERA_FOURCC="${D405_CAMERA_FOURCC:-YUYV}"
D405_CAMERA_BACKEND="${D405_CAMERA_BACKEND:-V4L2}"
D405_CAMERA_WARMUP_S="${D405_CAMERA_WARMUP_S:-0}"
D405_CAMERA_ASYNC_TIMEOUT_MS="${D405_CAMERA_ASYNC_TIMEOUT_MS:-500}"
D405_CAMERA_MAX_AGE_MS="${D405_CAMERA_MAX_AGE_MS:-1000}"
D405_CAMERA_REUSE_LAST_ON_TIMEOUT="${D405_CAMERA_REUSE_LAST_ON_TIMEOUT:-true}"
D405_CAMERA_WAIT_FOR_NEW_ON_STALE="${D405_CAMERA_WAIT_FOR_NEW_ON_STALE:-false}"
D405_CAMERA_REUSE_WARN_EVERY="${D405_CAMERA_REUSE_WARN_EVERY:-300}"
RECORD_SYNC_DIAGNOSTICS="${RECORD_SYNC_DIAGNOSTICS:-true}"
SYNC_WARN_AGE_MS="${SYNC_WARN_AGE_MS:-120}"
SYNC_WARN_EVERY="${SYNC_WARN_EVERY:-30}"
WRIST_CAM_WIDTH="${WRIST_CAM_WIDTH:-1920}"
WRIST_CAM_HEIGHT="${WRIST_CAM_HEIGHT:-1080}"
WRIST_CAM_FPS="${WRIST_CAM_FPS:-30}"
WRIST_CAMERA_REQUIRE_NEW="${WRIST_CAMERA_REQUIRE_NEW:-false}"
WRIST_CAMERA_REQUIRE_NEW_MODE="${WRIST_CAMERA_REQUIRE_NEW_MODE:-adaptive}"
WRIST_CAMERA_REQUIRE_NEW_MIN_AGE_MS="${WRIST_CAMERA_REQUIRE_NEW_MIN_AGE_MS:-28}"
WRIST_CAMERA_REQUIRE_NEW_TIMEOUT_S="${WRIST_CAMERA_REQUIRE_NEW_TIMEOUT_S:-0.012}"
WRIST_CAMERA_REQUIRE_NEW_FALLBACK_LAST="${WRIST_CAMERA_REQUIRE_NEW_FALLBACK_LAST:-true}"
FISH_CAMERA_FFMPEG_THREADS="${FISH_CAMERA_FFMPEG_THREADS:-1}"
FISH_CAMERA_UDP_FIFO_SIZE="${FISH_CAMERA_UDP_FIFO_SIZE:-1000000}"
FISH_CAMERA_FFMPEG_HWACCEL="${FISH_CAMERA_FFMPEG_HWACCEL:-}"
FISH_CAMERA_FFMPEG_DECODER="${FISH_CAMERA_FFMPEG_DECODER:-}"
FISH_CAMERA_FFMPEG_EXTRA_INPUT_ARGS="${FISH_CAMERA_FFMPEG_EXTRA_INPUT_ARGS:-}"
FISH_CAMERA_FFMPEG_EXTRA_OUTPUT_ARGS="${FISH_CAMERA_FFMPEG_EXTRA_OUTPUT_ARGS:-}"
X5_TACTILE_ASYNC_CACHE_MODE="${X5_TACTILE_ASYNC_CACHE_MODE:-full}"
X5_TACTILE_ASYNC_CACHE_MAIN_THREAD_WARMUP="${X5_TACTILE_ASYNC_CACHE_MAIN_THREAD_WARMUP:-false}"
X5_TACTILE_ASYNC_CACHE_STARTUP_TIMEOUT_S="${X5_TACTILE_ASYNC_CACHE_STARTUP_TIMEOUT_S:-2.0}"
X5_TACTILE_ASYNC_CACHE_STARTUP_MAX_AGE_MS="${X5_TACTILE_ASYNC_CACHE_STARTUP_MAX_AGE_MS:-120.0}"
WRIST_UNDISTORT="${WRIST_UNDISTORT:-false}"
WRIST_UNDISTORT_CROP_SIZE="${WRIST_UNDISTORT_CROP_SIZE:-896}"
WRIST_UNDISTORT_BALANCE="${WRIST_UNDISTORT_BALANCE:-0.0}"
WRIST_PROCESSED_ASYNC_CACHE="${WRIST_PROCESSED_ASYNC_CACHE:-false}"
WRIST_PROCESSED_ASYNC_CACHE_RETURN_COPY="${WRIST_PROCESSED_ASYNC_CACHE_RETURN_COPY:-false}"
WRIST_PROCESSED_ASYNC_CACHE_RAW_NO_COPY="${WRIST_PROCESSED_ASYNC_CACHE_RAW_NO_COPY:-true}"
WRIST_PROCESSED_ASYNC_CACHE_NONBLOCKING="${WRIST_PROCESSED_ASYNC_CACHE_NONBLOCKING:-true}"
WRIST_PROCESSED_ASYNC_CACHE_ALIGN_TO_CAPTURE_TIME="${WRIST_PROCESSED_ASYNC_CACHE_ALIGN_TO_CAPTURE_TIME:-false}"
WRIST_PROCESSED_ASYNC_CACHE_ALIGN_OFFSET_S="${WRIST_PROCESSED_ASYNC_CACHE_ALIGN_OFFSET_S:-0.0}"
WRIST_PROCESSED_ASYNC_CACHE_ALIGN_MAX_AGE_MS="${WRIST_PROCESSED_ASYNC_CACHE_ALIGN_MAX_AGE_MS:-250.0}"
WRIST_PROCESSED_ASYNC_CACHE_ALIGN_BUFFER_FRAMES="${WRIST_PROCESSED_ASYNC_CACHE_ALIGN_BUFFER_FRAMES:-45}"
WRIST_PROCESSED_ASYNC_CACHE_STARTUP_FRAMES="${WRIST_PROCESSED_ASYNC_CACHE_STARTUP_FRAMES:-3}"
WRIST_PROCESSED_ASYNC_CACHE_STARTUP_TIMEOUT_S="${WRIST_PROCESSED_ASYNC_CACHE_STARTUP_TIMEOUT_S:-3.0}"
WRIST_PROCESSED_ASYNC_CACHE_STARTUP_MAX_AGE_MS="${WRIST_PROCESSED_ASYNC_CACHE_STARTUP_MAX_AGE_MS:-120.0}"
WRIST_PROCESSED_ASYNC_CACHE_WARN_MS="${WRIST_PROCESSED_ASYNC_CACHE_WARN_MS:-8.0}"
WRIST_PROCESSED_ASYNC_CACHE_WARN_AGE_MS="${WRIST_PROCESSED_ASYNC_CACHE_WARN_AGE_MS:-120.0}"
WRIST_PROCESSED_ASYNC_CACHE_READ_TIMEOUT_S="${WRIST_PROCESSED_ASYNC_CACHE_READ_TIMEOUT_S:-0.2}"
WRIST_PROCESSED_ASYNC_CACHE_WORKERS="${WRIST_PROCESSED_ASYNC_CACHE_WORKERS:-1}"
WRIST_PROCESSED_ASYNC_CACHE_STATS_EVERY_S="${WRIST_PROCESSED_ASYNC_CACHE_STATS_EVERY_S:-1.0}"
WRIST_PIPELINE_MODE="${WRIST_PIPELINE_MODE:-queued}"
WRIST_UNDISTORT_WORKERS_PER_CAMERA="${WRIST_UNDISTORT_WORKERS_PER_CAMERA:-4}"
WRIST_RAW_QUEUE_FRAMES="${WRIST_RAW_QUEUE_FRAMES:-120}"
WRIST_PROCESSED_QUEUE_FRAMES="${WRIST_PROCESSED_QUEUE_FRAMES:-120}"
WRIST_PIPELINE_OVERFLOW_ACTION="${WRIST_PIPELINE_OVERFLOW_ACTION:-abort}"
WRIST_UNDISTORT_CALIB_FILE="${WRIST_UNDISTORT_CALIB_FILE:-}"
WRIST_UNDISTORT_LEFT_CALIB_FILE="${WRIST_UNDISTORT_LEFT_CALIB_FILE:-${LEFT_WRIST_UNDISTORT_CALIB_FILE:-}}"
WRIST_UNDISTORT_RIGHT_CALIB_FILE="${WRIST_UNDISTORT_RIGHT_CALIB_FILE:-${RIGHT_WRIST_UNDISTORT_CALIB_FILE:-}}"
WRIST_UNDISTORT_K="${WRIST_UNDISTORT_K:-}"
WRIST_UNDISTORT_D="${WRIST_UNDISTORT_D:-}"
WRIST_UNDISTORT_IMAGE_SIZE="${WRIST_UNDISTORT_IMAGE_SIZE:-}"
WRIST_UNDISTORT_LEFT_K="${WRIST_UNDISTORT_LEFT_K:-${LEFT_WRIST_UNDISTORT_K:-}}"
WRIST_UNDISTORT_LEFT_D="${WRIST_UNDISTORT_LEFT_D:-${LEFT_WRIST_UNDISTORT_D:-}}"
WRIST_UNDISTORT_LEFT_IMAGE_SIZE="${WRIST_UNDISTORT_LEFT_IMAGE_SIZE:-${LEFT_WRIST_UNDISTORT_IMAGE_SIZE:-}}"
WRIST_UNDISTORT_RIGHT_K="${WRIST_UNDISTORT_RIGHT_K:-${RIGHT_WRIST_UNDISTORT_K:-}}"
WRIST_UNDISTORT_RIGHT_D="${WRIST_UNDISTORT_RIGHT_D:-${RIGHT_WRIST_UNDISTORT_D:-}}"
WRIST_UNDISTORT_RIGHT_IMAGE_SIZE="${WRIST_UNDISTORT_RIGHT_IMAGE_SIZE:-${RIGHT_WRIST_UNDISTORT_IMAGE_SIZE:-}}"

CONNECT_LEFT_FORCE_SENSOR="${CONNECT_LEFT_FORCE_SENSOR:-true}"
CONNECT_RIGHT_FORCE_SENSOR="${CONNECT_RIGHT_FORCE_SENSOR:-true}"
FORCE_SENSOR_REQUIRED="${FORCE_SENSOR_REQUIRED:-true}"
FORCE_SENSOR_DATA_KEY="${FORCE_SENSOR_DATA_KEY:-zero_force_data}"
FORCE_SENSOR_READ_HZ="${FORCE_SENSOR_READ_HZ:-100}"
FORCE_SENSOR_CONNECT_TIMEOUT_S="${FORCE_SENSOR_CONNECT_TIMEOUT_S:-3.0}"
FORCE_SENSOR_CLEAR_ON_CONNECT="${FORCE_SENSOR_CLEAR_ON_CONNECT:-false}"
FORCE_SENSOR_CLEAR_ON_EPISODE_START="${FORCE_SENSOR_CLEAR_ON_EPISODE_START:-true}"
FORCE_SENSOR_CLEAR_SETTLE_S="${FORCE_SENSOR_CLEAR_SETTLE_S:-0.2}"
REALMAN_THREAD_MODE="${REALMAN_THREAD_MODE:-dual}"
REALMAN_DEFER_ASYNC_READERS="${REALMAN_DEFER_ASYNC_READERS:-true}"
LEROBOT_SEPARATE_EPISODE_VIDEOS="${LEROBOT_SEPARATE_EPISODE_VIDEOS:-true}"
GRIPPER_PREWARM_ON_EPISODE_START="${GRIPPER_PREWARM_ON_EPISODE_START:-true}"
GRIPPER_PREWARM_SEND_CURRENT_ACTION="${GRIPPER_PREWARM_SEND_CURRENT_ACTION:-false}"
TACTILE_STALE_GUARD="${TACTILE_STALE_GUARD:-true}"
TACTILE_STALE_ABORT="${TACTILE_STALE_ABORT:-true}"
TACTILE_STALE_MAX_REPEATS="${TACTILE_STALE_MAX_REPEATS:-6}"
TACTILE_STALE_WARN_EVERY="${TACTILE_STALE_WARN_EVERY:-30}"
TACTILE_STALE_MIN_KEYS="${TACTILE_STALE_MIN_KEYS:-1}"
TACTILE_RECONNECT_ON_EPISODE_START="${TACTILE_RECONNECT_ON_EPISODE_START:-auto}"
TACTILE_RECONNECT_SETTLE_S="${TACTILE_RECONNECT_SETTLE_S:-0.3}"
TACTILE_AUTO_RECONNECT_MAX_AGE_MS="${TACTILE_AUTO_RECONNECT_MAX_AGE_MS:-1000}"
TACTILE_AUTO_RECONNECT_MIN_FRAMES="${TACTILE_AUTO_RECONNECT_MIN_FRAMES:-10}"
TACTILE_AUTO_RECONNECT_MIN_FPS="${TACTILE_AUTO_RECONNECT_MIN_FPS:-1}"
CONNECT_TACTILE_SIDECAR="${CONNECT_TACTILE_SIDECAR:-false}"
CONNECT_X5_TACTILE="${CONNECT_X5_TACTILE:-true}"
TACTILE_SIDECAR_AUTOSTART="${TACTILE_SIDECAR_AUTOSTART:-true}"
TACTILE_SIDECAR_HOST="${TACTILE_SIDECAR_HOST:-127.0.0.1}"
TACTILE_SIDECAR_PORT="${TACTILE_SIDECAR_PORT:-61300}"
TACTILE_SIDECAR_TIMEOUT_S="${TACTILE_SIDECAR_TIMEOUT_S:-0.05}"
TACTILE_SIDECAR_CONNECT_TIMEOUT_S="${TACTILE_SIDECAR_CONNECT_TIMEOUT_S:-8.0}"
TACTILE_SIDECAR_START_TIMEOUT_S="${TACTILE_SIDECAR_START_TIMEOUT_S:-8.0}"
TACTILE_SIDECAR_REQUIRED="${TACTILE_SIDECAR_REQUIRED:-true}"
TACTILE_SIDECAR_WAIT_TIMEOUT_MS="${TACTILE_SIDECAR_WAIT_TIMEOUT_MS:-500}"
TACTILE_SIDECAR_LOG_INTERVAL_S="${TACTILE_SIDECAR_LOG_INTERVAL_S:-5.0}"
TACTILE_SIDECAR_BACKEND="${TACTILE_SIDECAR_BACKEND:-Flux}"
CAPTURE_LOOP_REALTIME_GUARD="${CAPTURE_LOOP_REALTIME_GUARD:-true}"
CAPTURE_LOOP_MAX_DT_RATIO="${CAPTURE_LOOP_MAX_DT_RATIO:-1.25}"
CAPTURE_LOOP_MAX_OVERRUNS="${CAPTURE_LOOP_MAX_OVERRUNS:-5}"
CAPTURE_LOOP_GUARD_GRACE_FRAMES="${CAPTURE_LOOP_GUARD_GRACE_FRAMES:-10}"
CAPTURE_LOOP_ABORT_ON_OVERRUN="${CAPTURE_LOOP_ABORT_ON_OVERRUN:-true}"
TACTILE_SAVE_RAW="${TACTILE_SAVE_RAW:-false}"
if [[ -z "${X5_TACTILE_MODALITIES+x}" ]]; then
  X5_TACTILE_MODALITIES="depth_deformation"
fi
if [[ "${TACTILE_SAVE_RAW,,}" =~ ^(1|true|yes|on)$ ]]; then
  if [[ ",${X5_TACTILE_MODALITIES,,}," != *",raw,"* ]]; then
    X5_TACTILE_MODALITIES="${X5_TACTILE_MODALITIES},raw"
  fi
fi
X5_TACTILE_MODE="${X5_TACTILE_MODE:-standard}"
case "${X5_TACTILE_MODE,,}" in
  high)
    TACTILE_WIDTH="${TACTILE_WIDTH:-384}"
    TACTILE_HEIGHT="${TACTILE_HEIGHT:-288}"
    ;;
  standard)
    TACTILE_WIDTH="${TACTILE_WIDTH:-128}"
    TACTILE_HEIGHT="${TACTILE_HEIGHT:-96}"
    ;;
  *)
    echo "[capture-app] ERROR: X5_TACTILE_MODE must be standard or high, got '${X5_TACTILE_MODE}'"
    exit 97
    ;;
esac
TACTILE_RAW_WIDTH="${TACTILE_RAW_WIDTH:-640}"
TACTILE_RAW_HEIGHT="${TACTILE_RAW_HEIGHT:-480}"

X5_TACTILE_FLUX_PC_HOST="${X5_TACTILE_FLUX_PC_HOST:-192.168.1.100}"
X5_TACTILE_MAX_FPS="${X5_TACTILE_MAX_FPS:-120}"
X5_TACTILE_FLUX_LEFT_LEFT_PC_PORT="${X5_TACTILE_FLUX_LEFT_LEFT_PC_PORT:-61000}"
X5_TACTILE_FLUX_LEFT_RIGHT_PC_PORT="${X5_TACTILE_FLUX_LEFT_RIGHT_PC_PORT:-61001}"
X5_TACTILE_FLUX_RIGHT_LEFT_PC_PORT="${X5_TACTILE_FLUX_RIGHT_LEFT_PC_PORT:-61002}"
X5_TACTILE_FLUX_RIGHT_RIGHT_PC_PORT="${X5_TACTILE_FLUX_RIGHT_RIGHT_PC_PORT:-61003}"
GRIPPER_ACTION_MODE="${GRIPPER_ACTION_MODE:-step}"
GRIPPER_SPEED="${GRIPPER_SPEED:-60}"
GRIPPER_MIN_POSITION="${GRIPPER_MIN_POSITION:-0}"
GRIPPER_MAX_POSITION="${GRIPPER_MAX_POSITION:-1000}"
GRIPPER_TORQUE_LIMIT="${GRIPPER_TORQUE_LIMIT:-90}"
GRIPPER_ACTION_SEND_HZ="${GRIPPER_ACTION_SEND_HZ:-50}"
LINGKONG_GRIPPER_STATUS_HZ="${LINGKONG_GRIPPER_STATUS_HZ:-50}"
GRIPPER_REQUIRED="${GRIPPER_REQUIRED:-true}"

for gripper_limit_name in \
  GRIPPER_MIN_POSITION \
  GRIPPER_MAX_POSITION \
  GRIPPER_TORQUE_LIMIT; do
  gripper_limit_value="${!gripper_limit_name}"
  if [[ ! "$gripper_limit_value" =~ ^[0-9]+$ ]]; then
    echo "[capture-app] ERROR: ${gripper_limit_name} must be an integer, got '${gripper_limit_value}'"
    exit 96
  fi
done
if (( GRIPPER_MIN_POSITION < 0 || GRIPPER_MAX_POSITION > 1000 || GRIPPER_MIN_POSITION > GRIPPER_MAX_POSITION )); then
  echo "[capture-app] ERROR: gripper position limits must satisfy 0 <= min <= max <= 1000"
  exit 96
fi
if (( GRIPPER_TORQUE_LIMIT < 10 || GRIPPER_TORQUE_LIMIT > 100 )); then
  echo "[capture-app] ERROR: GRIPPER_TORQUE_LIMIT must be within 10..100"
  exit 96
fi

export LEROBOT_ROOT
export PYTHONPATH="${PROJECT_ROOT}:${LEROBOT_ROOT}/src${PYTHONPATH:+:${PYTHONPATH}}"
export LD_LIBRARY_PATH="${CAPTURE_ENV_PREFIX}/lib:${LD_LIBRARY_PATH:-}"
export CAPTURE_PYTHON_BIN
export RUN_NAME DATASET_BASE_DIR DATASET_ROOT DATASET_REPO_ID TASK_INDEX FPS NUM_EPISODES EPISODE_TIME_S
export CAPTURE_UI_HOST CAPTURE_UI_PORT CAPTURE_OPEN_BROWSER
export VCODEC STREAMING_ENCODING ENCODER_THREADS ENCODER_QUEUE_MAXSIZE
export TACTILE_STREAMING_ENCODING TACTILE_ENCODER_THREADS TACTILE_ENCODER_NICE
export TACTILE_RAW_SPOOL_FINISH_TIMEOUT_S
export OPENCV_NUM_THREADS OPENCV_OPENCL
export CONNECT_WRIST_CAMERA CONNECT_LOCAL_CAMERAS CONNECT_SHARED_CAMERAS CONNECT_GRIPPER
export CONNECT_D405_CAMERA D405_CAMERA_NAME D405_CAMERA_DEVICE D405_CAMERA_WIDTH D405_CAMERA_HEIGHT
export D405_CAMERA_FPS D405_CAMERA_FOURCC D405_CAMERA_BACKEND D405_CAMERA_WARMUP_S
export D405_CAMERA_ASYNC_TIMEOUT_MS D405_CAMERA_MAX_AGE_MS D405_CAMERA_REUSE_LAST_ON_TIMEOUT
export D405_CAMERA_WAIT_FOR_NEW_ON_STALE D405_CAMERA_REUSE_WARN_EVERY
export RECORD_SYNC_DIAGNOSTICS SYNC_WARN_AGE_MS SYNC_WARN_EVERY
export WRIST_CAM_WIDTH WRIST_CAM_HEIGHT WRIST_CAM_FPS
export WRIST_CAMERA_REQUIRE_NEW WRIST_CAMERA_REQUIRE_NEW_MODE WRIST_CAMERA_REQUIRE_NEW_MIN_AGE_MS
export WRIST_CAMERA_REQUIRE_NEW_TIMEOUT_S WRIST_CAMERA_REQUIRE_NEW_FALLBACK_LAST
export FISH_CAMERA_FFMPEG_THREADS FISH_CAMERA_UDP_FIFO_SIZE
export FISH_CAMERA_FFMPEG_HWACCEL FISH_CAMERA_FFMPEG_DECODER
export FISH_CAMERA_FFMPEG_EXTRA_INPUT_ARGS FISH_CAMERA_FFMPEG_EXTRA_OUTPUT_ARGS
export X5_TACTILE_ASYNC_CACHE_MODE X5_TACTILE_ASYNC_CACHE_MAIN_THREAD_WARMUP
export X5_TACTILE_ASYNC_CACHE_STARTUP_TIMEOUT_S X5_TACTILE_ASYNC_CACHE_STARTUP_MAX_AGE_MS
export WRIST_UNDISTORT WRIST_UNDISTORT_CROP_SIZE WRIST_UNDISTORT_BALANCE
export WRIST_PROCESSED_ASYNC_CACHE WRIST_PROCESSED_ASYNC_CACHE_RETURN_COPY
export WRIST_PROCESSED_ASYNC_CACHE_RAW_NO_COPY WRIST_PROCESSED_ASYNC_CACHE_NONBLOCKING
export WRIST_PROCESSED_ASYNC_CACHE_ALIGN_TO_CAPTURE_TIME
export WRIST_PROCESSED_ASYNC_CACHE_ALIGN_OFFSET_S WRIST_PROCESSED_ASYNC_CACHE_ALIGN_MAX_AGE_MS
export WRIST_PROCESSED_ASYNC_CACHE_ALIGN_BUFFER_FRAMES
export WRIST_PROCESSED_ASYNC_CACHE_STARTUP_FRAMES
export WRIST_PROCESSED_ASYNC_CACHE_STARTUP_TIMEOUT_S WRIST_PROCESSED_ASYNC_CACHE_STARTUP_MAX_AGE_MS
export WRIST_PROCESSED_ASYNC_CACHE_WARN_MS WRIST_PROCESSED_ASYNC_CACHE_WARN_AGE_MS
export WRIST_PROCESSED_ASYNC_CACHE_READ_TIMEOUT_S
export WRIST_PROCESSED_ASYNC_CACHE_WORKERS WRIST_PROCESSED_ASYNC_CACHE_STATS_EVERY_S
export WRIST_PIPELINE_MODE WRIST_UNDISTORT_WORKERS_PER_CAMERA WRIST_TIMESTAMP_MODE WRIST_FRAME_CLOCK_FPS
export WRIST_RAW_QUEUE_FRAMES WRIST_PROCESSED_QUEUE_FRAMES WRIST_PIPELINE_OVERFLOW_ACTION
export WRIST_UNDISTORT_CALIB_FILE WRIST_UNDISTORT_LEFT_CALIB_FILE WRIST_UNDISTORT_RIGHT_CALIB_FILE
export WRIST_UNDISTORT_K WRIST_UNDISTORT_D WRIST_UNDISTORT_IMAGE_SIZE
export WRIST_UNDISTORT_LEFT_K WRIST_UNDISTORT_LEFT_D WRIST_UNDISTORT_LEFT_IMAGE_SIZE
export WRIST_UNDISTORT_RIGHT_K WRIST_UNDISTORT_RIGHT_D WRIST_UNDISTORT_RIGHT_IMAGE_SIZE
export CONNECT_LEFT_FORCE_SENSOR CONNECT_RIGHT_FORCE_SENSOR FORCE_SENSOR_REQUIRED
export FORCE_SENSOR_DATA_KEY FORCE_SENSOR_READ_HZ FORCE_SENSOR_CONNECT_TIMEOUT_S FORCE_SENSOR_CLEAR_ON_CONNECT
export FORCE_SENSOR_CLEAR_ON_EPISODE_START FORCE_SENSOR_CLEAR_SETTLE_S
export REALMAN_THREAD_MODE REALMAN_DEFER_ASYNC_READERS
export LEROBOT_SEPARATE_EPISODE_VIDEOS
export GRIPPER_PREWARM_ON_EPISODE_START GRIPPER_PREWARM_SEND_CURRENT_ACTION
export TACTILE_STALE_GUARD TACTILE_STALE_ABORT TACTILE_STALE_MAX_REPEATS
export TACTILE_STALE_WARN_EVERY TACTILE_STALE_MIN_KEYS
export TACTILE_RECONNECT_ON_EPISODE_START TACTILE_RECONNECT_SETTLE_S
export TACTILE_AUTO_RECONNECT_MAX_AGE_MS TACTILE_AUTO_RECONNECT_MIN_FRAMES TACTILE_AUTO_RECONNECT_MIN_FPS
export CONNECT_TACTILE_SIDECAR CONNECT_X5_TACTILE TACTILE_SIDECAR_AUTOSTART
export TACTILE_SIDECAR_HOST TACTILE_SIDECAR_PORT TACTILE_SIDECAR_TIMEOUT_S
export TACTILE_SIDECAR_CONNECT_TIMEOUT_S TACTILE_SIDECAR_START_TIMEOUT_S TACTILE_SIDECAR_REQUIRED
export TACTILE_SIDECAR_WAIT_TIMEOUT_MS TACTILE_SIDECAR_LOG_INTERVAL_S TACTILE_SIDECAR_BACKEND
export CAPTURE_LOOP_REALTIME_GUARD CAPTURE_LOOP_MAX_DT_RATIO CAPTURE_LOOP_MAX_OVERRUNS
export CAPTURE_LOOP_GUARD_GRACE_FRAMES CAPTURE_LOOP_ABORT_ON_OVERRUN
export TACTILE_SAVE_RAW X5_TACTILE_MODALITIES X5_TACTILE_MODE TACTILE_WIDTH TACTILE_HEIGHT
export TACTILE_RAW_WIDTH TACTILE_RAW_HEIGHT X5_TACTILE_FLUX_PC_HOST X5_TACTILE_MAX_FPS
export X5_TACTILE_FLUX_LEFT_LEFT_PC_PORT X5_TACTILE_FLUX_LEFT_RIGHT_PC_PORT
export X5_TACTILE_FLUX_RIGHT_LEFT_PC_PORT X5_TACTILE_FLUX_RIGHT_RIGHT_PC_PORT
export GRIPPER_ACTION_MODE GRIPPER_SPEED GRIPPER_MIN_POSITION GRIPPER_MAX_POSITION
export GRIPPER_TORQUE_LIMIT GRIPPER_ACTION_SEND_HZ LINGKONG_GRIPPER_STATUS_HZ GRIPPER_REQUIRED

echo "[capture-app] dataset root: ${DATASET_ROOT}"
echo "[capture-app] repo_id: ${DATASET_REPO_ID}"
echo "[capture-app] run_name=${RUN_NAME}"
echo "[capture-app] python entry: ${CAPTURE_APP_PY:-scripts/capture_realman_x5_force_app.py}"
echo "[capture-app] task_index=${TASK_INDEX} fps=${FPS} episodes=${NUM_EPISODES}"
echo "[capture-app] UI: http://${CAPTURE_UI_HOST}:${CAPTURE_UI_PORT}"
echo "[capture-app] video vcodec=${VCODEC} streaming_encoding=${STREAMING_ENCODING} encoder_threads=${ENCODER_THREADS} encoder_queue_maxsize=${ENCODER_QUEUE_MAXSIZE}"
echo "[capture-app] tactile streaming_encoding=${TACTILE_STREAMING_ENCODING} encoder_threads=${TACTILE_ENCODER_THREADS} nice=${TACTILE_ENCODER_NICE} raw_spool_finish_timeout_s=${TACTILE_RAW_SPOOL_FINISH_TIMEOUT_S}"
echo "[capture-app] opencv threads=${OPENCV_NUM_THREADS} opencl=${OPENCV_OPENCL}"
echo "[capture-app] wrist rgb request=${WRIST_CAM_WIDTH}x${WRIST_CAM_HEIGHT}@${WRIST_CAM_FPS}"
echo "[capture-app] wrist require_new=${WRIST_CAMERA_REQUIRE_NEW} mode=${WRIST_CAMERA_REQUIRE_NEW_MODE} min_age_ms=${WRIST_CAMERA_REQUIRE_NEW_MIN_AGE_MS} timeout_s=${WRIST_CAMERA_REQUIRE_NEW_TIMEOUT_S} fallback_last=${WRIST_CAMERA_REQUIRE_NEW_FALLBACK_LAST}"
echo "[capture-app] fish camera ffmpeg_threads=${FISH_CAMERA_FFMPEG_THREADS} udp_fifo_size=${FISH_CAMERA_UDP_FIFO_SIZE}"
echo "[capture-app] fish camera ffmpeg_hwaccel=${FISH_CAMERA_FFMPEG_HWACCEL:-none} decoder=${FISH_CAMERA_FFMPEG_DECODER:-auto}"
echo "[capture-app] x5 tactile async cache mode=${X5_TACTILE_ASYNC_CACHE_MODE} main_thread_warmup=${X5_TACTILE_ASYNC_CACHE_MAIN_THREAD_WARMUP} startup_timeout_s=${X5_TACTILE_ASYNC_CACHE_STARTUP_TIMEOUT_S} startup_max_age_ms=${X5_TACTILE_ASYNC_CACHE_STARTUP_MAX_AGE_MS}"
echo "[capture-app] wrist undistort=${WRIST_UNDISTORT} crop=${WRIST_UNDISTORT_CROP_SIZE} balance=${WRIST_UNDISTORT_BALANCE} left_calib=${WRIST_UNDISTORT_LEFT_CALIB_FILE:-${WRIST_UNDISTORT_CALIB_FILE:-<unset>}} right_calib=${WRIST_UNDISTORT_RIGHT_CALIB_FILE:-${WRIST_UNDISTORT_CALIB_FILE:-<unset>}}"
echo "[capture-app] wrist pipeline_mode=${WRIST_PIPELINE_MODE} timestamp_mode=${WRIST_TIMESTAMP_MODE:-frame_clock} frame_clock_fps=${WRIST_FRAME_CLOCK_FPS:-30} source_latency_frames=${WRIST_SOURCE_LATENCY_FRAMES:-0} source_latency_s=${WRIST_SOURCE_LATENCY_S:-0} undistort_workers_per_camera=${WRIST_UNDISTORT_WORKERS_PER_CAMERA} raw_queue_frames=${WRIST_RAW_QUEUE_FRAMES} processed_queue_frames=${WRIST_PROCESSED_QUEUE_FRAMES} overflow_action=${WRIST_PIPELINE_OVERFLOW_ACTION}"
echo "[capture-app] wrist processed_cache=${WRIST_PROCESSED_ASYNC_CACHE} workers=${WRIST_PROCESSED_ASYNC_CACHE_WORKERS} return_copy=${WRIST_PROCESSED_ASYNC_CACHE_RETURN_COPY} raw_no_copy=${WRIST_PROCESSED_ASYNC_CACHE_RAW_NO_COPY} nonblocking=${WRIST_PROCESSED_ASYNC_CACHE_NONBLOCKING} align_to_capture_time=${WRIST_PROCESSED_ASYNC_CACHE_ALIGN_TO_CAPTURE_TIME} align_offset_s=${WRIST_PROCESSED_ASYNC_CACHE_ALIGN_OFFSET_S} align_max_age_ms=${WRIST_PROCESSED_ASYNC_CACHE_ALIGN_MAX_AGE_MS} align_buffer_frames=${WRIST_PROCESSED_ASYNC_CACHE_ALIGN_BUFFER_FRAMES} warn_ms=${WRIST_PROCESSED_ASYNC_CACHE_WARN_MS} warn_age_ms=${WRIST_PROCESSED_ASYNC_CACHE_WARN_AGE_MS} read_timeout_s=${WRIST_PROCESSED_ASYNC_CACHE_READ_TIMEOUT_S} stats_every_s=${WRIST_PROCESSED_ASYNC_CACHE_STATS_EVERY_S}"
echo "[capture-app] wrist processed_cache startup_frames=${WRIST_PROCESSED_ASYNC_CACHE_STARTUP_FRAMES} startup_timeout_s=${WRIST_PROCESSED_ASYNC_CACHE_STARTUP_TIMEOUT_S} startup_max_age_ms=${WRIST_PROCESSED_ASYNC_CACHE_STARTUP_MAX_AGE_MS}"
echo "[capture-app] wrist undistort inline left_k=$([[ -n "${WRIST_UNDISTORT_LEFT_K:-${WRIST_UNDISTORT_K:-}}" ]] && echo set || echo unset) left_d=$([[ -n "${WRIST_UNDISTORT_LEFT_D:-${WRIST_UNDISTORT_D:-}}" ]] && echo set || echo unset) right_k=$([[ -n "${WRIST_UNDISTORT_RIGHT_K:-${WRIST_UNDISTORT_K:-}}" ]] && echo set || echo unset) right_d=$([[ -n "${WRIST_UNDISTORT_RIGHT_D:-${WRIST_UNDISTORT_D:-}}" ]] && echo set || echo unset)"
echo "[capture-app] d405 camera=${CONNECT_D405_CAMERA} name=${D405_CAMERA_NAME} device=${D405_CAMERA_DEVICE} request=${D405_CAMERA_WIDTH}x${D405_CAMERA_HEIGHT}@${D405_CAMERA_FPS} fourcc=${D405_CAMERA_FOURCC} backend=${D405_CAMERA_BACKEND} warmup_s=${D405_CAMERA_WARMUP_S} async_timeout_ms=${D405_CAMERA_ASYNC_TIMEOUT_MS} max_age_ms=${D405_CAMERA_MAX_AGE_MS} reuse_last=${D405_CAMERA_REUSE_LAST_ON_TIMEOUT} wait_for_new_on_stale=${D405_CAMERA_WAIT_FOR_NEW_ON_STALE}"
echo "[capture-app] sync diagnostics=${RECORD_SYNC_DIAGNOSTICS} warn_age_ms=${SYNC_WARN_AGE_MS} warn_every=${SYNC_WARN_EVERY}"
echo "[capture-app] force left=${CONNECT_LEFT_FORCE_SENSOR} right=${CONNECT_RIGHT_FORCE_SENSOR} required=${FORCE_SENSOR_REQUIRED} key=${FORCE_SENSOR_DATA_KEY}"
echo "[capture-app] force clear on connect=${FORCE_SENSOR_CLEAR_ON_CONNECT} on episode start=${FORCE_SENSOR_CLEAR_ON_EPISODE_START} settle=${FORCE_SENSOR_CLEAR_SETTLE_S}s"
echo "[capture-app] realman thread mode=${REALMAN_THREAD_MODE} defer_async_readers=${REALMAN_DEFER_ASYNC_READERS}"
echo "[capture-app] separate episode videos=${LEROBOT_SEPARATE_EPISODE_VIDEOS}"
echo "[capture-app] gripper prewarm=${GRIPPER_PREWARM_ON_EPISODE_START} send_current_action=${GRIPPER_PREWARM_SEND_CURRENT_ACTION}"
echo "[capture-app] gripper safety position=${GRIPPER_MIN_POSITION}..${GRIPPER_MAX_POSITION} torque<=${GRIPPER_TORQUE_LIMIT} speed=${GRIPPER_SPEED}"
echo "[capture-app] tactile stale guard=${TACTILE_STALE_GUARD} abort=${TACTILE_STALE_ABORT} max_repeats=${TACTILE_STALE_MAX_REPEATS}"
echo "[capture-app] realtime guard=${CAPTURE_LOOP_REALTIME_GUARD} max_dt_ratio=${CAPTURE_LOOP_MAX_DT_RATIO} max_overruns=${CAPTURE_LOOP_MAX_OVERRUNS} abort=${CAPTURE_LOOP_ABORT_ON_OVERRUN}"
echo "[capture-app] tactile reconnect on episode start=${TACTILE_RECONNECT_ON_EPISODE_START} settle=${TACTILE_RECONNECT_SETTLE_S}s"
echo "[capture-app] tactile source connect_x5=${CONNECT_X5_TACTILE} sidecar=${CONNECT_TACTILE_SIDECAR} sidecar_autostart=${TACTILE_SIDECAR_AUTOSTART} sidecar=${TACTILE_SIDECAR_HOST}:${TACTILE_SIDECAR_PORT} timeout_s=${TACTILE_SIDECAR_TIMEOUT_S} start_timeout_s=${TACTILE_SIDECAR_START_TIMEOUT_S}"
echo "[capture-app] tactile mode=${X5_TACTILE_MODE} modalities=${X5_TACTILE_MODALITIES} max_fps=${X5_TACTILE_MAX_FPS} output=${TACTILE_WIDTH}x${TACTILE_HEIGHT} raw_native=${TACTILE_RAW_WIDTH}x${TACTILE_RAW_HEIGHT} save_raw=${TACTILE_SAVE_RAW}"

if command -v ss >/dev/null 2>&1 && ss -ltn "sport = :${CAPTURE_UI_PORT}" | grep -q LISTEN; then
  echo "[capture-app] ERROR: UI port ${CAPTURE_UI_PORT} is already in use."
  echo "[capture-app] Run: CAPTURE_UI_PORT=${CAPTURE_UI_PORT} scripts/stop_capture_app.sh"
  echo "[capture-app] Or choose another port: CAPTURE_UI_PORT=8767 scripts/capture_realman_x5_force_app.sh"
  exit 98
fi

if [[ "${CONNECT_X5_TACTILE,,}" =~ ^(1|true|yes|on)$ ]] \
  && [[ ! "${CONNECT_TACTILE_SIDECAR,,}" =~ ^(1|true|yes|on)$ ]] \
  && command -v ss >/dev/null 2>&1; then
  occupied_tactile_ports=()
  for tactile_port in \
    "${X5_TACTILE_FLUX_LEFT_LEFT_PC_PORT}" \
    "${X5_TACTILE_FLUX_LEFT_RIGHT_PC_PORT}" \
    "${X5_TACTILE_FLUX_RIGHT_LEFT_PC_PORT}" \
    "${X5_TACTILE_FLUX_RIGHT_RIGHT_PC_PORT}"; do
    tactile_socket_line="$(ss -H -lunp 2>/dev/null | awk -v port=":${tactile_port}" '$4 ~ (port "$") {print; exit}')"
    if [[ -n "${tactile_socket_line}" ]]; then
      occupied_tactile_ports+=("${tactile_port}")
      echo "[capture-app] ERROR: X5 tactile UDP port ${tactile_port} is already in use: ${tactile_socket_line}" >&2
    fi
  done
  if [[ "${#occupied_tactile_ports[@]}" -gt 0 ]]; then
    echo "[capture-app] Another capture process owns required X5 tactile ports: ${occupied_tactile_ports[*]}" >&2
    echo "[capture-app] Stop that process first. scripts/stop_capture_app.sh reports external owners but will not kill another project." >&2
    exit 99
  fi
fi

CAPTURE_APP_PY="${CAPTURE_APP_PY:-scripts/capture_realman_x5_force_app.py}"

if [[ "${DRY_RUN:-false}" =~ ^(1|true|yes|on)$ ]]; then
  echo "[capture-app] DRY_RUN=true, not starting hardware capture."
  exit 0
fi

CAPTURE_CHILD_PID=""
CAPTURE_CHILD_STOPPED=false

capture_child_alive() {
  [[ -n "${CAPTURE_CHILD_PID}" ]] && kill -0 "${CAPTURE_CHILD_PID}" 2>/dev/null
}

signal_capture_child() {
  local sig="$1"
  [[ -n "${CAPTURE_CHILD_PID}" ]] || return 0
  kill "-${sig}" "-${CAPTURE_CHILD_PID}" 2>/dev/null || kill "-${sig}" "${CAPTURE_CHILD_PID}" 2>/dev/null || true
}

wait_capture_child_exit() {
  local timeout_s="$1"
  local end=$((SECONDS + timeout_s))
  while capture_child_alive && (( SECONDS < end )); do
    sleep 0.2
  done
  ! capture_child_alive
}

stop_capture_child() {
  local first_sig="${1:-INT}"
  if [[ "${CAPTURE_CHILD_STOPPED}" == "true" || -z "${CAPTURE_CHILD_PID}" ]]; then
    return 0
  fi
  CAPTURE_CHILD_STOPPED=true
  echo "[capture-app] stopping capture child pid=${CAPTURE_CHILD_PID} with ${first_sig}..."
  signal_capture_child "${first_sig}"
  wait_capture_child_exit 5 || {
    echo "[capture-app] capture child still running; sending TERM..."
    signal_capture_child TERM
  }
  wait_capture_child_exit 3 || {
    echo "[capture-app] capture child still running; sending KILL..."
    signal_capture_child KILL
  }
  wait "${CAPTURE_CHILD_PID}" 2>/dev/null || true
}

on_capture_int() {
  stop_capture_child INT
  exit 130
}

on_capture_term() {
  stop_capture_child TERM
  exit 143
}

trap on_capture_int INT
trap on_capture_term TERM

echo "[capture-app] python=${CAPTURE_PYTHON_BIN}"
if command -v setsid >/dev/null 2>&1; then
  setsid "${CAPTURE_PYTHON_BIN}" "$CAPTURE_APP_PY" "$@" &
else
  "${CAPTURE_PYTHON_BIN}" "$CAPTURE_APP_PY" "$@" &
fi
CAPTURE_CHILD_PID="$!"

set +e
wait "$CAPTURE_CHILD_PID"
status="$?"
set -e

trap - INT TERM
if [[ "$status" -ne 0 ]]; then
  stop_capture_child TERM
fi
exit "$status"
