#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

export CAPTURE_APP_PY="${CAPTURE_APP_PY:-scripts/capture_realman_x5_force_aligned_app.py}"

# Defaults for the aligned recorder. User-provided env still wins.
export WRIST_PROCESSED_ASYNC_CACHE="${WRIST_PROCESSED_ASYNC_CACHE:-true}"
export WRIST_PROCESSED_ASYNC_CACHE_RETURN_COPY="${WRIST_PROCESSED_ASYNC_CACHE_RETURN_COPY:-false}"
export WRIST_PROCESSED_ASYNC_CACHE_RAW_NO_COPY="${WRIST_PROCESSED_ASYNC_CACHE_RAW_NO_COPY:-true}"
export WRIST_PROCESSED_ASYNC_CACHE_NONBLOCKING="${WRIST_PROCESSED_ASYNC_CACHE_NONBLOCKING:-true}"
export WRIST_PROCESSED_ASYNC_CACHE_WORKERS="${WRIST_PROCESSED_ASYNC_CACHE_WORKERS:-2}"
export WRIST_PROCESSED_ASYNC_CACHE_READ_TIMEOUT_S="${WRIST_PROCESSED_ASYNC_CACHE_READ_TIMEOUT_S:-0.01}"
export WRIST_PROCESSED_ASYNC_CACHE_STATS_EVERY_S="${WRIST_PROCESSED_ASYNC_CACHE_STATS_EVERY_S:-0}"
export WRIST_PIPELINE_MODE="${WRIST_PIPELINE_MODE:-queued}"
export WRIST_UNDISTORT_WORKERS_PER_CAMERA="${WRIST_UNDISTORT_WORKERS_PER_CAMERA:-4}"
export WRIST_RAW_QUEUE_FRAMES="${WRIST_RAW_QUEUE_FRAMES:-120}"
export WRIST_PROCESSED_QUEUE_FRAMES="${WRIST_PROCESSED_QUEUE_FRAMES:-120}"
export WRIST_PIPELINE_OVERFLOW_ACTION="${WRIST_PIPELINE_OVERFLOW_ACTION:-abort}"
export WRIST_TIMESTAMP_MODE="${WRIST_TIMESTAMP_MODE:-frame_clock}"
export WRIST_FRAME_CLOCK_FPS="${WRIST_FRAME_CLOCK_FPS:-30}"
export WRIST_SOURCE_LATENCY_FRAMES="${WRIST_SOURCE_LATENCY_FRAMES:-0}"
export WRIST_SOURCE_LATENCY_S="${WRIST_SOURCE_LATENCY_S:-0}"
export WRIST_CAMERA_REQUIRE_NEW="${WRIST_CAMERA_REQUIRE_NEW:-false}"
export X5_TACTILE_ASYNC_CACHE="${X5_TACTILE_ASYNC_CACHE:-true}"
export ALIGNED_FORCE_PER_SENSOR_TACTILE_CACHE="${ALIGNED_FORCE_PER_SENSOR_TACTILE_CACHE:-true}"
if [[ "${ALIGNED_FORCE_PER_SENSOR_TACTILE_CACHE,,}" =~ ^(1|true|yes|on)$ ]]; then
  export X5_TACTILE_ASYNC_CACHE_MODE="per_sensor_thread"
else
  export X5_TACTILE_ASYNC_CACHE_MODE="${X5_TACTILE_ASYNC_CACHE_MODE:-per_sensor_thread}"
fi
export X5_TACTILE_ASYNC_CACHE_FPS="${X5_TACTILE_ASYNC_CACHE_FPS:-120}"
export X5_TACTILE_ASYNC_CACHE_HISTORY_SECONDS="${X5_TACTILE_ASYNC_CACHE_HISTORY_SECONDS:-12}"
export ALIGNED_TACTILE_USE_CACHE_HISTORY="${ALIGNED_TACTILE_USE_CACHE_HISTORY:-true}"
export ALIGNED_TACTILE_HISTORY_BATCH="${ALIGNED_TACTILE_HISTORY_BATCH:-1024}"
export TACTILE_PREVIEW_RGB_PASSTHROUGH="${TACTILE_PREVIEW_RGB_PASSTHROUGH:-false}"
export ALIGNED_TACTILE_PREVIEW_DIRECT_RGB="${ALIGNED_TACTILE_PREVIEW_DIRECT_RGB:-false}"
export ALIGNED_TACTILE_READ_DIRECT="${ALIGNED_TACTILE_READ_DIRECT:-false}"
export ALIGNED_TACTILE_DEBUG_EVERY_S="${ALIGNED_TACTILE_DEBUG_EVERY_S:-0}"
export TACTILE_RECONNECT_ON_EPISODE_START="${TACTILE_RECONNECT_ON_EPISODE_START:-auto}"
export ALIGNED_TACTILE_MONITOR_DURING_EPISODE="${ALIGNED_TACTILE_MONITOR_DURING_EPISODE:-false}"
export ALIGNED_TACTILE_RECONNECT_ON_STALL="${ALIGNED_TACTILE_RECONNECT_ON_STALL:-false}"
export ALIGNED_TACTILE_RECONNECT_DURING_EPISODE="${ALIGNED_TACTILE_RECONNECT_DURING_EPISODE:-false}"
export ALIGNED_TACTILE_STALL_TIMEOUT_S="${ALIGNED_TACTILE_STALL_TIMEOUT_S:-3.0}"
export ALIGNED_PRESTART_STREAMING_ENCODERS="${ALIGNED_PRESTART_STREAMING_ENCODERS:-true}"
export ALIGNED_ENCODER_WARM_START="${ALIGNED_ENCODER_WARM_START:-true}"
export ALIGNED_ENCODER_WARM_START_TIMEOUT_S="${ALIGNED_ENCODER_WARM_START_TIMEOUT_S:-5.0}"
export ALIGNED_CLEAR_BUFFERS_AFTER_ENCODER_PRESTART="${ALIGNED_CLEAR_BUFFERS_AFTER_ENCODER_PRESTART:-true}"
export ALIGNED_ENCODER_PRESTART_SETTLE_S="${ALIGNED_ENCODER_PRESTART_SETTLE_S:-0.8}"
export ALIGNED_POST_ENCODER_STARTUP_TIMEOUT_S="${ALIGNED_POST_ENCODER_STARTUP_TIMEOUT_S:-5.0}"
export ALIGNED_POST_ENCODER_STABLE_S="${ALIGNED_POST_ENCODER_STABLE_S:-0.6}"
export ALIGNED_POST_ENCODER_MIN_UPDATES="${ALIGNED_POST_ENCODER_MIN_UPDATES:-3}"
export ALIGNED_WRITER_DELAY_S="${ALIGNED_WRITER_DELAY_S:-0.45}"
export ALIGNED_WRIST_READ_TIMEOUT_S="${ALIGNED_WRIST_READ_TIMEOUT_S:-0.002}"
export ALIGNED_WRIST_POLL_HZ="${ALIGNED_WRIST_POLL_HZ:-120}"
export ALIGNED_WRIST_READY_TIMEOUT_S="${ALIGNED_WRIST_READY_TIMEOUT_S:-0.2}"
export ALIGNED_VISUAL_MAX_AGE_MS="${ALIGNED_VISUAL_MAX_AGE_MS:-120}"
export ALIGNED_WRIST_MAX_AGE_MS="${ALIGNED_WRIST_MAX_AGE_MS:-120}"
export ALIGNED_WRIST_PREFERRED_MAX_OFFSET_MS="${ALIGNED_WRIST_PREFERRED_MAX_OFFSET_MS:-40}"
export ALIGNED_D405_MAX_AGE_MS="${ALIGNED_D405_MAX_AGE_MS:-200}"
export ALIGNED_TACTILE_MAX_AGE_MS="${ALIGNED_TACTILE_MAX_AGE_MS:-250}"
export ALIGNED_BUFFER_SECONDS="${ALIGNED_BUFFER_SECONDS:-4}"
export ALIGNED_STATE_BUFFER_SECONDS="${ALIGNED_STATE_BUFFER_SECONDS:-8}"
export ALIGNED_WRIST_BUFFER_SECONDS="${ALIGNED_WRIST_BUFFER_SECONDS:-8}"
export ALIGNED_D405_BUFFER_SECONDS="${ALIGNED_D405_BUFFER_SECONDS:-6}"
export ALIGNED_TACTILE_BUFFER_SECONDS="${ALIGNED_TACTILE_BUFFER_SECONDS:-8}"
export ALIGNED_STRICT_NO_HOLD="${ALIGNED_STRICT_NO_HOLD:-true}"
export ALIGNED_HOLD_LAST_ON_STALE="${ALIGNED_HOLD_LAST_ON_STALE:-false}"
export ALIGNED_VISUAL_HOLD_MAX_AGE_MS="${ALIGNED_VISUAL_HOLD_MAX_AGE_MS:-1000}"
export ALIGNED_STATE_MAX_AGE_MS="${ALIGNED_STATE_MAX_AGE_MS:-150}"
export ALIGNED_ACTION_MAX_AGE_MS="${ALIGNED_ACTION_MAX_AGE_MS:-250}"
export ALIGNED_ABORT_ON_MISSING="${ALIGNED_ABORT_ON_MISSING:-true}"
export ALIGNED_WRITER_QUEUE_MAXSIZE="${ALIGNED_WRITER_QUEUE_MAXSIZE:-240}"
export ALIGNED_DATASET_SEAL_AFTER_SAVE="${ALIGNED_DATASET_SEAL_AFTER_SAVE:-true}"
export ALIGNED_DATASET_SNAPSHOT_AFTER_SAVE="${ALIGNED_DATASET_SNAPSHOT_AFTER_SAVE:-true}"
export ALIGNED_DATASET_SNAPSHOT_KEEP="${ALIGNED_DATASET_SNAPSHOT_KEEP:-2}"
export ALIGNED_DATASET_RESTORE_ON_ERROR="${ALIGNED_DATASET_RESTORE_ON_ERROR:-true}"
export FOOT_PEDAL_CONTROL="${FOOT_PEDAL_CONTROL:-false}"
export FOOT_PEDAL_DEVICE="${FOOT_PEDAL_DEVICE:-/dev/input/by-id/usb-PCsensor_FS20Pro-event-kbd}"
export FOOT_PEDAL_GRAB="${FOOT_PEDAL_GRAB:-true}"
export FOOT_PEDAL_START_KEY="${FOOT_PEDAL_START_KEY:-KEY_ESC}"
export FOOT_PEDAL_FINISH_KEY="${FOOT_PEDAL_FINISH_KEY:-KEY_LEFT}"
export FOOT_PEDAL_DISCARD_KEY="${FOOT_PEDAL_DISCARD_KEY:-KEY_RIGHT}"
export FOOT_PEDAL_DEBOUNCE_S="${FOOT_PEDAL_DEBOUNCE_S:-0.25}"
export FOOT_PEDAL_TWO_PEDAL_STOP_ENABLED="${FOOT_PEDAL_TWO_PEDAL_STOP_ENABLED:-false}"
export FOOT_PEDAL_TWO_PEDAL_WINDOW_S="${FOOT_PEDAL_TWO_PEDAL_WINDOW_S:-0.0}"
export TRAJECTORY_GRIPPER_CONTROL_ENABLED="${TRAJECTORY_GRIPPER_CONTROL_ENABLED:-false}"
export TRAJECTORY_GRIPPER_CONTROL_HOST="${TRAJECTORY_GRIPPER_CONTROL_HOST:-127.0.0.1}"
export TRAJECTORY_GRIPPER_CONTROL_PORT="${TRAJECTORY_GRIPPER_CONTROL_PORT:-8767}"
if [[ -z "${CAPTURE_CONTROL_MODE:-}" ]]; then
  if [[ -n "${GRIPPER_COMMAND_SOURCE:-}" ]]; then
    CAPTURE_CONTROL_MODE="${GRIPPER_COMMAND_SOURCE}"
  elif [[ "${TRAJECTORY_GRIPPER_CONTROL_ENABLED,,}" =~ ^(1|true|yes|on)$ ]]; then
    CAPTURE_CONTROL_MODE=program
  else
    CAPTURE_CONTROL_MODE=leader
  fi
fi
CAPTURE_CONTROL_MODE="${CAPTURE_CONTROL_MODE,,}"
if [[ "${CAPTURE_CONTROL_MODE}" == "program" ]]; then
  GRIPPER_COMMAND_SOURCE=program
  export TRAJECTORY_GRIPPER_CONTROL_ENABLED=true
  export SEND_ACTION_ENABLED=false
  export SEND_GRIPPER_ACTION_ENABLED=true
  export GRIPPER_PREWARM_ON_EPISODE_START=false
elif [[ "${CAPTURE_CONTROL_MODE}" == "leader" ]]; then
  GRIPPER_COMMAND_SOURCE=leader
  export TRAJECTORY_GRIPPER_CONTROL_ENABLED=false
  export SEND_ACTION_ENABLED="${SEND_ACTION_ENABLED:-false}"
  export SEND_GRIPPER_ACTION_ENABLED="${SEND_GRIPPER_ACTION_ENABLED:-true}"
elif [[ "${CAPTURE_CONTROL_MODE}" == "drag" ]]; then
  # Drag mode records follower joint state as the joint action. Only the
  # gripper command continues to come from the leader arm.
  GRIPPER_COMMAND_SOURCE=leader
  export TRAJECTORY_GRIPPER_CONTROL_ENABLED=false
  export SEND_ACTION_ENABLED=false
  export SEND_GRIPPER_ACTION_ENABLED=true
else
  echo "[capture-app] ERROR: CAPTURE_CONTROL_MODE must be leader, program, or drag" >&2
  exit 2
fi
export CAPTURE_CONTROL_MODE GRIPPER_COMMAND_SOURCE
export DRAG_ACTION_STATE_MAX_AGE_MS="${DRAG_ACTION_STATE_MAX_AGE_MS:-150}"
export LEADER_PARTIAL_FALLBACK_TO_STATE="${LEADER_PARTIAL_FALLBACK_TO_STATE:-true}"
export LEADER_FALLBACK_STATE_MAX_AGE_MS="${LEADER_FALLBACK_STATE_MAX_AGE_MS:-${DRAG_ACTION_STATE_MAX_AGE_MS}}"
export DRAG_FORCE_PRECISE="${DRAG_FORCE_PRECISE:-true}"
export DRAG_SINGULAR_WALL="${DRAG_SINGULAR_WALL:-true}"
export EPISODE_RIGHT_ARM_RESET_ENABLED="${EPISODE_RIGHT_ARM_RESET_ENABLED:-false}"
export EPISODE_RIGHT_ARM_HOME_JOINTS_DEG="${EPISODE_RIGHT_ARM_HOME_JOINTS_DEG:-0.251,-0.385,5.442,90.016,0.627,89.769,0.167}"
export EPISODE_RIGHT_ARM_RESET_JOINTS_DEG="${EPISODE_RIGHT_ARM_RESET_JOINTS_DEG:-${EPISODE_RIGHT_ARM_HOME_JOINTS_DEG}}"
export EPISODE_RIGHT_ARM_RESET_SPEED="${EPISODE_RIGHT_ARM_RESET_SPEED:-10}"
export EPISODE_RIGHT_ARM_RESET_TOLERANCE_DEG="${EPISODE_RIGHT_ARM_RESET_TOLERANCE_DEG:-0.5}"
export EPISODE_RIGHT_ARM_RESET_MAX_START_DELTA_DEG="${EPISODE_RIGHT_ARM_RESET_MAX_START_DELTA_DEG:-45}"
export EPISODE_RIGHT_ARM_RESET_TIMEOUT_S="${EPISODE_RIGHT_ARM_RESET_TIMEOUT_S:-45}"
export EPISODE_RIGHT_ARM_RESET_POLL_HZ="${EPISODE_RIGHT_ARM_RESET_POLL_HZ:-20}"
export EPISODE_RIGHT_ARM_RESET_STABLE_SAMPLES="${EPISODE_RIGHT_ARM_RESET_STABLE_SAMPLES:-3}"
export EPISODE_RIGHT_ARM_RESET_SETTLE_S="${EPISODE_RIGHT_ARM_RESET_SETTLE_S:-0.5}"
export EPISODE_RIGHT_ARM_RESET_STATE_MAX_AGE_S="${EPISODE_RIGHT_ARM_RESET_STATE_MAX_AGE_S:-0.25}"
export EPISODE_RIGHT_ARM_RESET_QUERY_CONTROLLER_LIMITS="${EPISODE_RIGHT_ARM_RESET_QUERY_CONTROLLER_LIMITS:-false}"
export EPISODE_RIGHT_ARM_RESET_STOP_DRAG_FIRST="${EPISODE_RIGHT_ARM_RESET_STOP_DRAG_FIRST:-true}"
export EPISODE_RIGHT_ARM_RESET_PAUSE_READERS="${EPISODE_RIGHT_ARM_RESET_PAUSE_READERS:-true}"
export EPISODE_RETURN_TO_START_ENABLED="${EPISODE_RETURN_TO_START_ENABLED:-false}"
export EPISODE_RETURN_TO_START_SPEED="${EPISODE_RETURN_TO_START_SPEED:-5}"
export EPISODE_RETURN_TO_START_TOLERANCE_DEG="${EPISODE_RETURN_TO_START_TOLERANCE_DEG:-0.5}"
export EPISODE_RETURN_TO_START_MAX_DELTA_DEG="${EPISODE_RETURN_TO_START_MAX_DELTA_DEG:-60}"
export EPISODE_RETURN_TO_START_TIMEOUT_S="${EPISODE_RETURN_TO_START_TIMEOUT_S:-60}"
export EPISODE_RETURN_TO_START_POLL_HZ="${EPISODE_RETURN_TO_START_POLL_HZ:-20}"
export EPISODE_RETURN_TO_START_STABLE_SAMPLES="${EPISODE_RETURN_TO_START_STABLE_SAMPLES:-3}"
export EPISODE_RETURN_TO_START_SETTLE_S="${EPISODE_RETURN_TO_START_SETTLE_S:-0.5}"
export EPISODE_RETURN_TO_START_QUERY_CONTROLLER_LIMITS="${EPISODE_RETURN_TO_START_QUERY_CONTROLLER_LIMITS:-false}"
export EPISODE_RETURN_TO_START_PAUSE_READERS="${EPISODE_RETURN_TO_START_PAUSE_READERS:-true}"
export EPISODE_RETURN_TO_START_RESTORE_GRIPPER="${EPISODE_RETURN_TO_START_RESTORE_GRIPPER:-false}"
export EPISODE_RETURN_TO_START_GRIPPER_SPEED="${EPISODE_RETURN_TO_START_GRIPPER_SPEED:-30}"
export EPISODE_RETURN_TO_START_GRIPPER_TOLERANCE="${EPISODE_RETURN_TO_START_GRIPPER_TOLERANCE:-25}"
export EPISODE_RETURN_TO_START_GRIPPER_TIMEOUT_S="${EPISODE_RETURN_TO_START_GRIPPER_TIMEOUT_S:-10}"
export READY_GRIPPER_FOLLOW_ENABLED="${READY_GRIPPER_FOLLOW_ENABLED:-true}"
export READY_GRIPPER_FOLLOW_HZ="${READY_GRIPPER_FOLLOW_HZ:-30}"
export READY_GRIPPER_TAKEOVER_TOLERANCE="${READY_GRIPPER_TAKEOVER_TOLERANCE:-75}"
export READY_GRIPPER_PAUSE_SETTLE_S="${READY_GRIPPER_PAUSE_SETTLE_S:-0.10}"
export PROGRAM_GRIPPER_INITIAL_POSITION="${PROGRAM_GRIPPER_INITIAL_POSITION:-950}"
echo "[capture-app] control mode=${CAPTURE_CONTROL_MODE} gripper source=${GRIPPER_COMMAND_SOURCE} send_action=${SEND_ACTION_ENABLED} send_gripper=${SEND_GRIPPER_ACTION_ENABLED} leader_partial_fallback=${LEADER_PARTIAL_FALLBACK_TO_STATE} drag_force_precise=${DRAG_FORCE_PRECISE} drag_singular_wall=${DRAG_SINGULAR_WALL}"
if [[ "${EPISODE_RIGHT_ARM_RESET_ENABLED,,}" =~ ^(1|true|yes|on)$ ]]; then
  retired_home="11.623,8,-9.641,113.377,-0.763,60.717,2.797"
  if [[ "${EPISODE_RIGHT_ARM_RESET_JOINTS_DEG}" == "${retired_home}" ]]; then
    echo "[capture-app] ERROR: command still contains retired right-arm Home: ${retired_home}" >&2
    echo "[capture-app] Replace it with: EPISODE_RIGHT_ARM_RESET_JOINTS_DEG=${EPISODE_RIGHT_ARM_HOME_JOINTS_DEG}" >&2
    exit 2
  fi
  echo "[capture-app] per-episode right-arm reset enabled target_deg=${EPISODE_RIGHT_ARM_RESET_JOINTS_DEG:-<unset>} speed=${EPISODE_RIGHT_ARM_RESET_SPEED}% tolerance_deg=${EPISODE_RIGHT_ARM_RESET_TOLERANCE_DEG} max_start_delta_deg=${EPISODE_RIGHT_ARM_RESET_MAX_START_DELTA_DEG} timeout_s=${EPISODE_RIGHT_ARM_RESET_TIMEOUT_S} stop_drag_first=${EPISODE_RIGHT_ARM_RESET_STOP_DRAG_FIRST} pause_readers=${EPISODE_RIGHT_ARM_RESET_PAUSE_READERS}; left arm receives no reset command"
fi
if [[ "${EPISODE_RETURN_TO_START_ENABLED,,}" =~ ^(1|true|yes|on)$ ]]; then
  echo "[capture-app] dynamic right-arm return enabled: capture arm+gripper state on start, return arm after finish/discard arm_speed=${EPISODE_RETURN_TO_START_SPEED}% restore_gripper=${EPISODE_RETURN_TO_START_RESTORE_GRIPPER} tolerance_deg=${EPISODE_RETURN_TO_START_TOLERANCE_DEG} max_delta_deg=${EPISODE_RETURN_TO_START_MAX_DELTA_DEG}; left arm receives no return command"
fi

exec scripts/capture_realman_x5_force_app.sh "$@"
